# Generated by Django 4.2 on 2023-04-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizadores',
            name='utilizador',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='utilizadores',
            name='matricula',
            field=models.CharField(default='', max_length=20),
        ),
    ]
