# Generated by Django 4.2 on 2023-04-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_utilizadores_utilizador_alter_utilizadores_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilizadores',
            old_name='utilizador',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='utilizadores',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='utilizadores',
            name='localidade',
            field=models.CharField(choices=[('areias', 'Areias'), ('cajazeiras', 'Cajazeiras')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='utilizadores',
            name='matricula',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
