# Generated by Django 4.2 on 2023-04-18 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0007_alter_reserva_matricula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reserva'},
        ),
        migrations.AlterModelOptions(
            name='utilizadores',
            options={'verbose_name': 'Utilizadores', 'verbose_name_plural': 'Utilizadores'},
        ),
    ]
