# Generated by Django 4.2 on 2023-04-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0008_alter_reserva_options_alter_utilizadores_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='localidade_reserva',
            field=models.CharField(choices=[('areias', 'Areias'), ('cajazeiras', 'Cajazeiras')], default='', max_length=100),
        ),
    ]
