# Generated by Django 4.2 on 2023-04-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0010_alter_reserva_data_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='opcao_refeicao',
            field=models.CharField(choices=[('lanche_manha', 'Lanche da Manhã'), ('almoco', 'Almoço'), ('lanche_tarde', 'Lanche da Tarde'), ('jantar', 'Jantar')], default='', max_length=100),
        ),
    ]
