# Generated by Django 4.2 on 2023-04-18 01:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0011_reserva_opcao_refeicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='opcao_refeicao',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('lanche_manha', 'Lanche da Manhã'), ('almoco', 'Almoço'), ('lanche_tarde', 'Lanche da Tarde'), ('jantar', 'Jantar')], default='', max_length=100),
        ),
    ]
