# Generated by Django 5.0.4 on 2024-04-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidade', models.CharField(default='', max_length=100, verbose_name='Localidade')),
            ],
            options={
                'verbose_name': 'Localidades',
                'verbose_name_plural': 'Localidades',
            },
        ),
    ]
