# Generated by Django 5.0.4 on 2024-04-18 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_refeicao_delete_refeicoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_utilizador', models.CharField(max_length=20, unique=True)),
                ('nome_utilizador', models.CharField(default='', max_length=30)),
                ('email_utilizador', models.EmailField(default='', max_length=254, unique=True)),
                ('localidade_utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.localidades')),
            ],
            options={
                'verbose_name': 'Utilizadores',
                'verbose_name_plural': 'Utilizadores',
            },
        ),
    ]
