# Generated by Django 5.0.4 on 2024-04-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_utilizadores_email_utilizador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizadores',
            name='nome_utilizador',
            field=models.CharField(default='', max_length=50, verbose_name='Nome'),
        ),
    ]
