# Generated by Django 5.0.4 on 2024-04-18 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_utilizadores_nome_utilizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizadores',
            name='refeicao_utilizador',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='cadastros.refeicao', verbose_name='Refeições'),
            preserve_default=False,
        ),
    ]
