# Generated by Django 5.0.4 on 2024-04-19 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_alter_localidades_options_alter_refeicao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizadores',
            name='refeicao_utilizador',
            field=models.ForeignKey(choices=[(6, 'Café da Manhã'), (7, 'Lanche da manhã'), (8, 'Almoço'), (9, 'Lanche da tarde'), (10, 'Jantar')], on_delete=django.db.models.deletion.CASCADE, to='cadastros.refeicao', verbose_name='Refeições'),
        ),
    ]
