# Generated by Django 5.0.4 on 2024-04-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_remove_utilizadores_refeicao_utilizador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizadores',
            name='localidade_utilizador',
        ),
        migrations.AddField(
            model_name='utilizadores',
            name='localidade_utilizador',
            field=models.ManyToManyField(to='cadastros.localidades', verbose_name='Localidade'),
        ),
    ]
