# Generated by Django 5.0.4 on 2024-04-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_remove_utilizadores_localidade_utilizador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizadores',
            name='token_utilizador',
            field=models.CharField(default='', max_length=10, verbose_name='Token'),
        ),
    ]
