# Generated by Django 5.0.4 on 2024-04-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_utilizadores_token_utilizador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizadores',
            name='token_utilizador',
            field=models.ImageField(blank=True, upload_to='code'),
        ),
    ]
