# Generated by Django 5.0.4 on 2024-04-21 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_alter_utilizadores_token_utilizador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizadores',
            name='token_utilizador',
        ),
    ]
