# Generated by Django 5.0.4 on 2024-04-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_remove_utilizadores_token_utilizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidades',
            name='sigla_localidade',
            field=models.CharField(default='', max_length=10, verbose_name='Sigla'),
        ),
    ]
