# Generated by Django 5.0.4 on 2024-04-23 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_localidades_sigla_localidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localidades',
            name='sigla_localidade',
        ),
    ]
